# Generated by Django 6.0.2 on 2026-02-28 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('messaggio', models.TextField()),
                ('tipo', models.CharField(choices=[('BOOKING_PENDING', 'Richiesta in attesa'), ('BOOKING_APPROVED', 'Prenotazione approvata'), ('BOOKING_REJECTED', 'Prenotazione rifiutata')], max_length=50)),
                ('letta', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to='Utente.utente')),
            ],
            options={
                'db_table': 'Notifica',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['utente', 'letta'], name='Notifica_utente__402e6e_idx')],
            },
        ),
    ]
