# Generated by Django 5.2.9 on 2025-12-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Risorsa', '0001_initial'),
        ('Utente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('stato', models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default='True', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risorsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazione', to='Risorsa.risorsa')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='Utente.utente')),
            ],
            options={
                'db_table': 'Prenotazione',
            },
        ),
    ]
