# Generated by Django 5.2.9 on 2025-12-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRisorsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TipoRisorsa',
            },
        ),
        migrations.CreateModel(
            name='Risorsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descrizione', models.CharField(max_length=200)),
                ('is_available', models.BooleanField()),
                ('capacita', models.IntegerField(default=1)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risorse', to='Risorsa.tiporisorsa')),
            ],
            options={
                'db_table': 'Risorsa',
            },
        ),
    ]
