# Generated by Django 5.2.10 on 2026-02-01 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Risorsa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risorsa',
            name='is_available',
        ),
        migrations.AddField(
            model_name='risorsa',
            name='attiva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='risorsa',
            name='domenica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='risorsa',
            name='giovedi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='risorsa',
            name='lunedi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='risorsa',
            name='martedi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='risorsa',
            name='mercoledi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='risorsa',
            name='orario_apertura',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='risorsa',
            name='orario_chiusura',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='risorsa',
            name='sabato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='risorsa',
            name='venerdi',
            field=models.BooleanField(default=True),
        ),
    ]
