# Generated by Django 5.2.11 on 2026-02-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Risorsa', '0002_remove_risorsa_is_available_risorsa_attiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporisorsa',
            name='immagine_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
