# Generated by Django 5.2.12 on 2026-03-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Risorsa', '0003_tiporisorsa_immagine_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risorsa',
            name='attiva',
        ),
        migrations.AddField(
            model_name='risorsa',
            name='stato',
            field=models.CharField(choices=[('ATTIVA', 'Attiva'), ('MANUTENZIONE', 'In manutenzione'), ('DISATTIVA', 'Disattiva')], default='ATTIVA', max_length=20),
        ),
    ]
