# Generated by Django 5.2.12 on 2026-03-09 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Prenotazione', '0003_prenotazionepartecipante'),
        ('Utente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azione', models.CharField(choices=[('CREATA', 'Prenotazione creata'), ('CONFERMATA', 'Prenotazione confermata'), ('ANNULLATA', 'Prenotazione annullata'), ('RIFIUTATA', 'Prenotazione rifiutata'), ('PARTECIPANTE_RIFIUTATO', 'Partecipante ha rifiutato'), ('PARTECIPANTE_ACCETTATO', 'Partecipante ha accettato')], max_length=30)),
                ('descrizione', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prenotazione', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='Prenotazione.prenotazione')),
                ('utente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='Utente.utente')),
            ],
            options={
                'db_table': 'ActivityLog',
                'ordering': ['-created_at'],
            },
        ),
    ]
