# Generated by Django 5.2.9 on 2025-12-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utente',
            table='Utente',
        ),
    ]
