# Generated by Django 5.2.12 on 2026-03-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utente', '0002_alter_utente_ruolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='ruolo',
            field=models.CharField(choices=[('DIPENDENTE', 'dipendente'), ('RESPONSABILE', 'responsabile'), ('ADMIN', 'amministratore')], max_length=120),
        ),
    ]
