# Generated by Django 5.2.10 on 2026-02-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prenotazione', '0001_initial'),
        ('Risorsa', '0002_remove_risorsa_is_available_risorsa_attiva_and_more'),
        ('Utente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prenotazione',
            options={'ordering': ['-data_inizio']},
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='motivo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='stato',
            field=models.CharField(choices=[('PENDING', 'In attesa'), ('CONFERMATA', 'Confermata'), ('ANNULLATA', 'Annullata')], default='PENDING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='prenotazione',
            index=models.Index(fields=['risorsa', 'data_inizio', 'data_fine'], name='Prenotazion_risorsa_c4df49_idx'),
        ),
        migrations.AddIndex(
            model_name='prenotazione',
            index=models.Index(fields=['stato', 'data_inizio'], name='Prenotazion_stato_7f5160_idx'),
        ),
    ]
