# Generated by Django 5.2.12 on 2026-03-08 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prenotazione', '0002_alter_prenotazione_options_prenotazione_motivo_and_more'),
        ('Utente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotazionePartecipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('INVITATO', 'Invitato'), ('ACCETTATO', 'Accettato'), ('RIFIUTATO', 'Rifiutato')], default='INVITATO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prenotazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipanti', to='Prenotazione.prenotazione')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipazioni', to='Utente.utente')),
            ],
            options={
                'db_table': 'PrenotazionePartecipante',
                'unique_together': {('prenotazione', 'utente')},
            },
        ),
    ]
