# Generated by Django 5.2.17 on 2026-08-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prenotazione', '0003_prenotazionepartecipante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='motivo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
