# Generated by Django 5.2.12 on 2026-03-16 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prenotazione', '0003_prenotazionepartecipante'),
        ('Prenotazione', '0004_seed_prenotazione'),
    ]

    operations = [
    ]
