# Generated by Django 5.2.9 on 2025-12-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Risorsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='risorsa',
            table='Risorsa',
        ),
        migrations.AlterModelTable(
            name='tiporisorsa',
            table='TipoRisorsa',
        ),
    ]
